plugin: aws_ec2
regions:
  - us-east-1

filters:
  tag:Project: ACS730
  tag:Team: zombies

keyed_groups:
  - key: tags.Name
    prefix: tag_Name
  - key: placement.availability_zone
    prefix: az

hostnames:
  - public-ip-address
  - tag:Name
  - dns-name
  - private-dns-name

compose:
  ansible_host: public_ip_address
  ansible_user: "ec2-user"
  ansible_ssh_private_key_file: "/home/runner/.ssh/zombies-key"
  ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
