---
- name: Configure Bastion Host (Webserver 2)
  hosts: tag_Name_zombies-webserver2
  become: yes
  vars:
    ansible_user: ec2-user 
    ansible_ssh_private_key_file: ~/.ssh/zombieacs730
    s3_bucket: "zombies-acs730"
    team_name: "zombies"
    webserver_id: 2

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Install required packages
      yum:
        name:
          - httpd
          - awscli
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy image from S3
      command: "aws s3 cp s3://{{ s3_bucket }}/web-content/webserver{{ webserver_id }}.jpg /var/www/html/"
      args:
        creates: "/var/www/html/webserver{{ webserver_id }}.jpg"

    - name: Get instance private IP
      set_fact:
        private_ip: "{{ ansible_host }}"

    - name: Create index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      vars:
        hostname: "{{ ansible_hostname }}"
        ip_address: "{{ private_ip }}"

    - name: Configure SSH forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^AllowTcpForwarding', line: 'AllowTcpForwarding yes' }
        - { regexp: '^GatewayPorts', line: 'GatewayPorts yes' }

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted 
