name: Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
  push:
    branches: [ staging, prod ]
    paths:
      - 'Terraform/**'
      - 'Ansible/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_DIR: Terraform/${{ github.event.inputs.environment || 'staging' }}
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: true

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Select Terraform Workspace
        run: |
          echo "Current TF_WORKSPACE: $TF_WORKSPACE"
          terraform workspace list
          terraform workspace show
          unset TF_WORKSPACE
          terraform workspace select ${{ github.event.inputs.environment || 'staging' }} || \
          terraform workspace new ${{ github.event.inputs.environment || 'staging' }}
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -out tf.plan
          terraform show -no-color tf.plan > plan.txt
        working-directory: ${{ env.TF_DIR }} 
        continue-on-error: true

      - name: Post Plan to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync(`${process.env.TF_DIR}/plan.txt`, 'utf8');
            const maxLength = 65536;
            const chunks = [];
            
            for (let i = 0; i < plan.length; i += maxLength) {
              chunks.push(plan.slice(i, i + maxLength));
            }
            
            for (let i = 0; i < chunks.length; i++) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: `### Terraform Plan (Part ${i + 1}/${chunks.length})\n\`\`\`\n${chunks[i]}\n\`\`\``
              });
            }

      - name: Terraform Apply
        if: |
          (github.ref == 'refs/heads/staging' && github.event.inputs.environment == 'staging') ||
          (github.ref == 'refs/heads/prod' && github.event.inputs.environment == 'prod')
        run: terraform apply -input=false -auto-approve tf.plan
        working-directory: ${{ env.TF_DIR }}

      - name: Verify Deployment
        if: success()
        run: |
          echo "Verifying infrastructure deployment..."
          terraform output -json > tf_output.json
        working-directory: ${{ env.TF_DIR }}

  ansible:
    needs: terraform
    name: "Ansible Configuration"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Install Ansible Collections
        run: ansible-galaxy collection install amazon.aws

      - name: Wait for EC2 Instances
        run: |
          echo "Waiting for EC2 instances to be ready..."
          sleep 90

      - name: Run Ansible Playbook - Bastion
        working-directory: ./Ansible
        run: |
          ansible-playbook -i inventory/aws_ec2.yml playbooks/bastion.yml
        continue-on-error: false

      - name: Run Ansible Playbook - Webservers
        working-directory: ./Ansible
        run: |
          ansible-playbook -i inventory/aws_ec2.yml playbooks/webserver.yml
        continue-on-error: false

      - name: Verify Web Services
        if: success()
        run: |
          echo "Verifying web services..."
          curl -f http://<web-server-ip>/health || exit 1

  notify:
    needs: [terraform, ansible]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Deployment Status
        uses: actions/github-script@v6
        with:
          script: |
            const terraform_status = '${{ needs.terraform.result }}';
            const ansible_status = '${{ needs.ansible.result }}';
            const environment = '${{ github.event.inputs.environment || 'staging' }}';
            
            let status = '✅ Deployment Successful!';
            if (terraform_status !== 'success' || ansible_status !== 'success') {
              status = '❌ Deployment Failed!';
            }
            
            const message = `### Deployment Status to ${environment}
            - Terraform: ${terraform_status}
            - Ansible: ${ansible_status}
            
            ${status}`;
            
            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: message
              });
            }

  promote-to-prod:
    name: Promote to Production
    needs: [terraform, ansible]
    if: ${{ github.ref == 'refs/heads/staging' && success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Production Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Infrastructure Deployment"
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: prod
          inputs: |
            environment: prod
