name: Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
  push:
    branches: [ staging, prod ]
    paths:
      - 'Terraform/**'
      - 'Ansible/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: true

      - name: Set Deployment Environment Variables
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment || (github.ref == 'refs/heads/prod' && 'prod') || 'staging' }}"
          echo "DEPLOY_ENV=$ENVIRONMENT" >> $GITHUB_ENV
          echo "TF_DIR=Terraform/$ENVIRONMENT" >> $GITHUB_ENV

      - name: Terraform Format
        run: terraform fmt -check -recursive
        continue-on-error: true
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Select Terraform Workspace
        run: |
          unset TF_WORKSPACE
          terraform workspace select $DEPLOY_ENV || terraform workspace new $DEPLOY_ENV
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tf.plan
        working-directory: ${{ env.TF_DIR }}
        continue-on-error: true

      - name: Debug Plan File Existence
        run: |
          if [ -f tf.plan ]; then
            echo "Plan file exists!"
          else
            echo "Plan file does not exist!"
            exit 1
          fi
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        if: |
          (github.ref == 'refs/heads/staging') ||
          (github.ref == 'refs/heads/prod' && github.event.inputs.environment == 'prod')
        run: terraform apply -input=false -auto-approve tf.plan
        working-directory: ${{ env.TF_DIR }}

      - name: Verify Deployment
        if: success()
        run: terraform output -json > tf_output.json
        working-directory: ${{ env.TF_DIR }}

      - name: Export Webserver IP
        id: extract_outputs
        run: |
          WEB_IP=$(jq -r .webserver4_public_ip.value tf_output.json)
          echo "WEB_IP=$WEB_IP" >> $GITHUB_ENV
          echo "Webserver IP: $WEB_IP"
          if [ -z "$WEB_IP" ]; then
            echo "❌ WEB_IP is empty. Check Terraform outputs."
            exit 1
          fi
        working-directory: ${{ env.TF_DIR }}

  ansible:
    needs: terraform
    name: "Ansible Configuration"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Install Ansible Collections
        run: ansible-galaxy collection install amazon.aws

      - name: Wait for EC2 Instances
        run: sleep 90

      - name: Run Ansible Playbook - Bastion
        working-directory: ./Ansible
        run: ansible-playbook -i inventory/aws_ec2.yml playbooks/bastion.yml

      - name: Run Ansible Playbook - Webservers
        working-directory: ./Ansible
        run: ansible-playbook -i inventory/aws_ec2.yml playbooks/webserver.yml

      - name: Check Webserver IP
        run: |
          echo "WEB_IP is: $WEB_IP"
          if [ -z "$WEB_IP" ]; then
            echo "❌ WEB_IP is not set!"
            exit 1
          fi

      - name: Verify Web Services
        if: success()
        run: curl -f http://$WEB_IP/health || exit 1

  notify:
    needs: [terraform, ansible]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Deployment Status
        uses: actions/github-script@v6
        with:
          script: |
            const terraform_status = '${{ needs.terraform.result }}';
            const ansible_status = '${{ needs.ansible.result }}';
            const environment = '${{ github.event.inputs.environment || 'staging' }}';
            let status = '✅ Deployment Successful!';
            if (terraform_status !== 'success' || ansible_status !== 'success') {
              status = '❌ Deployment Failed!';
            }
            const message = `### Deployment Status to ${environment}
            - Terraform: ${terraform_status}
            - Ansible: ${ansible_status}
            
            ${status}`;
            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: message
              });
            }

  promote-to-prod:
    name: Promote to Production
    needs: [terraform, ansible]
    if: ${{ github.ref == 'refs/heads/staging' && success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Production Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Infrastructure Deployment"
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: prod
          inputs: |
            environment: prod
